#spring:
#  application:
#    name: ad-eureka
#
#server:
#  port: 8000
#
#eureka:
#  instance:
#    hostname: localhost
#
#  client:
#  #是否从注册中心获取注册信息
#    fetch-registry: false
#  # 是否将自己注册到注册中心
#    register-with-eureka: false
#    #与eureka服务器通信的地址
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#
---
spring:
  application:
    name: ad-eureka
  profiles: server1
server:
  port: 8000
eureka:
  instance:
    hostname: server1
    # 是否使用ip地址注册
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server2
server:
  port: 8001
eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server3:8002/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: server3
server:
  port: 8002
eureka:
  instance:
    hostname: server3
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/
